name: Check docker image

on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        images: [
          { base: 'azinchen/duplicacy', target: 'chaosexanima/duplicacy' },
          { base: 'ghcr.io/mastodon/mastodon:nightly', target: 'chaosexanima/mastodon' },
          { base: 'ghcr.io/mastodon/mastodon-streaming:nightly', target: 'chaosexanima/mastodon-streaming' },
          { base: 'ghcr.io/nanos/fedifetcher', target: 'chaosexanima/fedifetcher' },
        ]
    runs-on: ubuntu-latest
    outputs:
      needs-updating: ${{ steps.check.outputs.needs-updating }}
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v2.0.0
        with:
          base-image:  ${{ matrix.images.base }}
          image:   ${{ matrix.images.target }}

  build:
    runs-on: ubuntu-latest
    needs: check
    if: needs.check.outputs.needs-updating == 'true'
    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker compose build --pull --push
